version: '3.8'
services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - jenkins

networks:
  jenkins:

volumes:
  jenkins_home:
